PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE stations( id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name varchar(100), url varchar(100), status boolean);
INSERT INTO stations VALUES(1,'Rádio Onda Sul 94.9 FM','https://ice.fabricahost.com.br/ondasulfm',0);
INSERT INTO stations VALUES(2,'Rádio Liderança 91.3 FM','https://s28.maxcast.com.br:8868/live',0);
INSERT INTO stations VALUES(3,'Rádio Clube News 90.9 FM','https://servidor14-3.brlogic.com:7540/live',0);
INSERT INTO stations VALUES(4,'Rádio Sol Nascente DF','https://s05.maxcast.com.br:8242/live',0);
INSERT INTO stations VALUES(5,'Rádio Voz Poços','https://stm1.radionline.top:7088/stream',0);
INSERT INTO stations VALUES(6,'Rádio Onda Sul 100.7 FM','https://stm01.virtualcast.com.br:8886/live',0);
INSERT INTO stations VALUES(7,'Rádio Alternativa 104.9 FM','https://conecta.welltecnologia.com.br/radio/8200/stream',0);
INSERT INTO stations VALUES(8,'Rádio Energia 97.7 FM','https://streaming.inweb.com.br/energia',0);
INSERT INTO stations VALUES(9,'Black In Love Radio','https://hts05.kshost.com.br:9890/live',0);
INSERT INTO stations VALUES(10,'Plus Rádio Fortaleza','https://hts02.kshost.com.br:13168/live',0);
INSERT INTO stations VALUES(11,'Rádio Hot 107 FM','https://9772.brasilstream.com.br/stream',0);
INSERT INTO stations VALUES(12,'Radio Rivadavia 630 AM','https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac',0);
INSERT INTO stations VALUES(13,'Rádio CV Mais 97.5 FM','https://ssl1.transmissaodigital.com:20098/',0);
INSERT INTO stations VALUES(14,'Bom Gosto','https://ssl.xcast.com.br:11408/stream',0);
INSERT INTO stations VALUES(15,'Rádio Clube Sul de Minas 103.1 FM','https://ice.fabricahost.com.br/clubefmvarginha',0);
INSERT INTO stations VALUES(16,'Rádio Rota Do Rodeio','https://hts04.kshost.com.br:12986/live',0);
INSERT INTO stations VALUES(17,'Rádio Band FM 101.1','https://stm01.virtualcast.com.br:8216/live',0);
INSERT INTO stations VALUES(18,'Rádio Melodia 102.3 FM','https://server01.ouvir.radio.br:8033/stream',0);
INSERT INTO stations VALUES(19,'Rádio Cristã de Maringá','https://hts03.kshost.com.br:12156/live',0);
INSERT INTO stations VALUES(20,'Caracol Radio 100.9 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CARACOL_RADIOAAC.aac',0);
INSERT INTO stations VALUES(21,'Rádio Nova Cultura 93.1 FM','https://streaming.ei3.com.br/radio/8010/stream',0);
INSERT INTO stations VALUES(22,'Rádio CBN Rio 92.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_RJAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(23,'Radio Carve 850 AM','https://radiolatina.live/9202/stream',0);
INSERT INTO stations VALUES(24,'Rádio Super 91.7 FM','https://9134.brasilstream.com.br/mp3',0);
INSERT INTO stations VALUES(25,'Bons Tempos FM','https://server02.ouvir.radio.br:8050/stream',0);
INSERT INTO stations VALUES(26,'Rádio Imigrantes 100.9 FM','https://sonic.lestetronics.com.br:7001/',0);
INSERT INTO stations VALUES(27,'Web Vintage Radio','https://s1.voscast.com:10563/webvintage',0);
INSERT INTO stations VALUES(28,'Radio El Espectador 810 AM','https://espectador1.net.com.uy:8122/stream',0);
INSERT INTO stations VALUES(29,'Rádio Costa do Sol 101.7 FM','https://ice.fabricahost.com.br/radiocostadosol',0);
INSERT INTO stations VALUES(30,'Rádio Arena 103.1 FM','https://stm12.xcast.com.br:7672/stream',0);
INSERT INTO stations VALUES(31,'1000 Hits Love','https://ais-sa2.cdnstream1.com/2210_128.mp3',0);
INSERT INTO stations VALUES(32,'Rádio Jovem Pira 102.7 FM','https://servidor23-5.brlogic.com:7722/live',0);
INSERT INTO stations VALUES(33,'Rádio Shekinah só Louvor','https://player.voxpainel.com.br/proxy/7076',0);
INSERT INTO stations VALUES(34,'Alternativa Esportes Webrádio','https://hts08.kshost.com.br:12592/live',0);
INSERT INTO stations VALUES(35,'Rádio Hits 99.7 FM','https://paineldj.com.br:20028/stream',0);
INSERT INTO stations VALUES(36,'Rádio Banda B 550 AM 79.3 FM','https://ice.fabricahost.com.br/bandabctb',0);
INSERT INTO stations VALUES(37,'Rádio João Pessoa 97.7 FM','https://serv3.audiovox.pw:7084/stream',0);
INSERT INTO stations VALUES(38,'Web Rádio Piabanha','https://s11.maxcast.com.br:8168/live',0);
INSERT INTO stations VALUES(39,'Rádio Gospel Adorando','https://r15.ciclano.io:14391/stream',0);
INSERT INTO stations VALUES(40,'MS Web Rádio','https://s25.maxcast.com.br:8108/live',0);
INSERT INTO stations VALUES(41,'Rádio Estação Pop','https://s46.maxcast.com.br:8026/live',0);
INSERT INTO stations VALUES(42,'Rádio Nova Geração FM','https://www.appradio.app:8152/live',0);
INSERT INTO stations VALUES(43,'Rádio Integração 87.5 FM','https://cast.tendaweb.com.br/proxy/radiointegracaofm?mp=/stream',0);
INSERT INTO stations VALUES(44,'Rádio Nova Brasil 89.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/NOVABRASIL_RIOAAC.aac',0);
INSERT INTO stations VALUES(45,'Rádio Rambo Metal','https://s01.maxcast.com.br:8063/live',0);
INSERT INTO stations VALUES(46,'Rádio Musical Gospel','https://stm1.xcast.com.br:8258/stream',0);
INSERT INTO stations VALUES(47,'Rádio CBN São Paulo 90.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_SPAAC.aac',0);
INSERT INTO stations VALUES(48,'Rádio 98 FM','https://9554.brasilstream.com.br/stream',0);
INSERT INTO stations VALUES(49,'Rádio Referência Do Samba','https://stm6.srvvox.com.br:7290/stream',0);
INSERT INTO stations VALUES(50,'Radio Saudade 99.7 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/SAUDADE_FMAAC.aac',0);
INSERT INTO stations VALUES(51,'Rádio Jovem Pan 107.3 FM','https://server01.ouvir.radio.br:8042/stream',0);
INSERT INTO stations VALUES(52,'Rádio BH FM 102.1','https://playerservices.streamtheworld.com/api/livestream-redirect/BHFMAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(53,'Rádio Saquarema Surf Rock','https://servidor17.brlogic.com:7202/live',0);
INSERT INTO stations VALUES(54,'Radio Antena 2 650 AM','https://playerservices.streamtheworld.com/api/livestream-redirect/ANTENA_2_BOG_SC',0);
INSERT INTO stations VALUES(55,'Super Rádio Tupi 96.5 FM','https://8923.brasilstream.com.br/stream',0);
INSERT INTO stations VALUES(56,'Cidade Light','https://stm1.voxplayer.com.br:7126/',0);
INSERT INTO stations VALUES(57,'Rádio Tropical 95.3 FM','https://solid24.streamupsolutions.com/proxy/dcofieen?mp=/stream',0);
INSERT INTO stations VALUES(58,'Radio Guavira 103.1 FM','https://player.srvaudio.com.br/player-ssl/11504/',0);
INSERT INTO stations VALUES(59,'Rádio Fla Gol','https://s17.maxcast.com.br:8168/live?id=824974197929',0);
INSERT INTO stations VALUES(60,'Rádio Cidade das Águas 101.3 FM','https://str1.streamhostpg.com.br:8008/stream',0);
INSERT INTO stations VALUES(61,'Rádio Super Pajeú 99.3 FM','https://server3.webradios.com.br:19434/9434',0);
INSERT INTO stations VALUES(62,'Radio Gospel Life','https://s15.maxcast.com.br:8296/live',0);
INSERT INTO stations VALUES(63,'Europe 1 104.7 FM','https://ais-live.cloud-services.paris/europe1.mp3',0);
INSERT INTO stations VALUES(64,'Rádio CBN Brasília 95.3 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_BSBAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(65,'Radio Caravana 750 AM','https://streamingecuador.net:9006/stream',0);
INSERT INTO stations VALUES(66,'Rádio 96 FM Bauru','https://streaming.ei3.com.br/radio/8000/mp3',0);
INSERT INTO stations VALUES(67,'Rádio Morada Sertaneja','https://hts02.kshost.com.br:12594/live',0);
INSERT INTO stations VALUES(68,'Esportes Total','https://s03.maxcast.com.br:8006/live',0);
INSERT INTO stations VALUES(69,'Rádio Visionária','https://hts06.kshost.com.br:11956/live',0);
INSERT INTO stations VALUES(70,'Rádio Nativa 92.5 FM','https://player.srvaudio.com.br/player-ssl/9468/',0);
INSERT INTO stations VALUES(71,'Rádio Saudade Web','https://player-ssl.painelstream.net:9036/live',0);
INSERT INTO stations VALUES(72,'Acesita FM','https://stm1.xcast.com.br:9470/stream',0);
INSERT INTO stations VALUES(73,'Rádio Globo RJ 98.1 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_GLOBO_RJAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(74,'Rádio Sinai Web Gospel','https://centova4.transmissaodigital.com:20278/stream',0);
INSERT INTO stations VALUES(75,'Rádio Trans Mundial - RTM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOTRANSMUNDIALAAC_SC',0);
INSERT INTO stations VALUES(76,'Rádio Excesso FM 90.9','https://excessocast.com.br/radio/8000/excessofm',0);
INSERT INTO stations VALUES(77,'Rádio Nova 89.5 FM','https://server2.webradios.com.br:19128/9128',0);
INSERT INTO stations VALUES(78,'Rádio Inconfidência 100.9 FM','https://ssl.zoeweb.net/proxy/inconfidencia?mp=/stream',0);
INSERT INTO stations VALUES(79,'Radio Rock On','https://streaming.radiostreamlive.com/radiorockon_devices',0);
INSERT INTO stations VALUES(80,'Rádio Dracena','https://cc3.streammaximum.com:20001/stream',0);
INSERT INTO stations VALUES(81,'Rádio Positividade 104.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/POSITIVIDADE_FM.mp3',0);
INSERT INTO stations VALUES(82,'Rádio Ativa Mais HD','https://player.srvaudio.com.br/player-ssl/11460/',0);
INSERT INTO stations VALUES(83,'Web Vinil RN','https://ssl.srvstm.com:6704/',0);
INSERT INTO stations VALUES(84,'Bons Tempos FM','https://server02.ouvir.radio.br:8050/stream',0);
INSERT INTO stations VALUES(85,'Rádio Tom Brasil','https://streaming.radioempresabrasil.com.br/proxy/tombrasil/stream',0);
INSERT INTO stations VALUES(86,'Rádio Grande Serra 90.9 FM','https://streaming.rmpsite.com.br/rgsararipina/',0);
INSERT INTO stations VALUES(87,'Rádio Keops FM','https://player.srvsh.com.br/proxy/7016',0);
INSERT INTO stations VALUES(88,'Rádio Band FM 101.1','https://stm01.virtualcast.com.br:8216/live',0);
INSERT INTO stations VALUES(89,'Rádio Globo RJ 98.1 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_GLOBO_RJAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(90,'Rádio CV Mais 97.5 FM','https://ssl1.transmissaodigital.com:20098/',0);
INSERT INTO stations VALUES(91,'Radio Jazz Medley','https://server01.ouvir.radio.br:8006/stream',0);
INSERT INTO stations VALUES(92,'Rádio João Pessoa 97.7 FM','https://serv3.audiovox.pw:7084/stream',0);
INSERT INTO stations VALUES(93,'Rádio 96 FM Bauru','https://streaming.ei3.com.br/radio/8000/mp3',0);
INSERT INTO stations VALUES(94,'Rádio CBN São Paulo 90.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_SPAAC.aac',0);
INSERT INTO stations VALUES(95,'Rádio Fla Gol','https://s17.maxcast.com.br:8168/live?id=824974197929',0);
INSERT INTO stations VALUES(96,'Rádio Liderança 91.3 FM','https://s28.maxcast.com.br:8868/live',0);
INSERT INTO stations VALUES(97,'Rádio Gospel Adorando','https://r15.ciclano.io:14391/stream',0);
INSERT INTO stations VALUES(98,'Acesita FM','https://stm1.xcast.com.br:9470/stream',0);
INSERT INTO stations VALUES(99,'Rádio Costa do Sol 101.7 FM','https://ice.fabricahost.com.br/radiocostadosol',0);
INSERT INTO stations VALUES(100,'Rádio Nova Cultura 93.1 FM','https://streaming.ei3.com.br/radio/8010/stream',0);
INSERT INTO stations VALUES(101,'Radio Gospel Life','https://s15.maxcast.com.br:8296/live',0);
INSERT INTO stations VALUES(102,'Rádio Hits 99.7 FM','https://paineldj.com.br:20028/stream',0);
INSERT INTO stations VALUES(103,'Rádio BH FM 102.1','https://playerservices.streamtheworld.com/api/livestream-redirect/BHFMAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(104,'Flash Disco Dance','https://stm1.srvif.com:21764/',0);
INSERT INTO stations VALUES(105,'Rádio Nova Geração FM','https://www.appradio.app:8152/live',0);
INSERT INTO stations VALUES(106,'Rádio Vida Melhor 105.5 FM','https://servidor32-4.brlogic.com:8480/live',0);
INSERT INTO stations VALUES(107,'Cidade Light','https://stm1.voxplayer.com.br:7126/',0);
INSERT INTO stations VALUES(108,'Rádio Hits HD','https://casthttps1.suaradionanet.net/13388/stream',0);
INSERT INTO stations VALUES(109,'Rádio Caiuás','https://s32.maxcast.com.br:8092/live',0);
INSERT INTO stations VALUES(110,'Rádio Shekinah só Louvor','https://player.voxpainel.com.br/proxy/7076',0);
INSERT INTO stations VALUES(111,'Rádio CBN Rio 92.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_RJAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(112,'Rádio Super Gospel Vale','https://ssl.hdradios.net:7394/stream',0);
INSERT INTO stations VALUES(113,'Rádio Cidade das Águas 101.3 FM','https://str1.streamhostpg.com.br:8008/stream',0);
INSERT INTO stations VALUES(114,'Rádio Saquarema Surf Rock','https://servidor17.brlogic.com:7202/live',0);
INSERT INTO stations VALUES(115,'Rádio Na Voz Delas','https://player.painelvox.com/player-ssl/8694',0);
INSERT INTO stations VALUES(116,'Disco Funk','https://s30.maxcast.com.br:8084/live',0);
INSERT INTO stations VALUES(117,'Flash Disco Dance 80','https://stm1.srvif.com:6676/',0);
INSERT INTO stations VALUES(118,'Alternativa Esportes Webrádio','https://hts08.kshost.com.br:12592/live',0);
INSERT INTO stations VALUES(119,'Web Vintage Radio','https://s1.voscast.com:10563/webvintage',0);
INSERT INTO stations VALUES(120,'Rádio Band 95.5 FM','https://cast4.hoost.com.br:20216/stream',0);
INSERT INTO stations VALUES(121,'Rádio Sol Nascente DF','https://s05.maxcast.com.br:8242/live',0);
INSERT INTO stations VALUES(122,'Radio Saudade 99.7 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/SAUDADE_FMAAC.aac',0);
INSERT INTO stations VALUES(123,'Rádio Hot 107 FM','https://9772.brasilstream.com.br/stream',0);
INSERT INTO stations VALUES(124,'Rádio Capitania','https://hts09.kshost.com.br:12600/live',0);
INSERT INTO stations VALUES(125,'Rádio Cidade Itajubá Light','https://cast4.zadax.com.br:8104/live',0);
INSERT INTO stations VALUES(126,'Rádio Canoa Grande 90.7 FM','https://servidor39.brlogic.com:8300/live',0);
INSERT INTO stations VALUES(127,'Rádio Rota Do Rodeio','https://hts04.kshost.com.br:12986/live',0);
INSERT INTO stations VALUES(128,'Rádio Zonadez','https://stm22.srvaudio.com.br:10056/stream',0);
INSERT INTO stations VALUES(129,'Rádio Clube News 90.9 FM','https://servidor14-3.brlogic.com:7540/live',0);
INSERT INTO stations VALUES(130,'Rádio Energia 97.7 FM','https://streaming.inweb.com.br/energia',0);
INSERT INTO stations VALUES(131,'Web Rádio Verdão','https://s45.hstbr.net:8062/live',0);
INSERT INTO stations VALUES(132,'Rádio Alternativa 104.9 FM','https://conecta.welltecnologia.com.br/radio/8200/stream',0);
INSERT INTO stations VALUES(133,'Rádio Rambo Metal','https://s01.maxcast.com.br:8063/live',0);
INSERT INTO stations VALUES(134,'Super Rádio Tupi 96.5 FM','https://8923.brasilstream.com.br/stream',0);
INSERT INTO stations VALUES(135,'Rádio Excesso FM 90.9','https://excessocast.com.br/radio/8000/excessofm',0);
INSERT INTO stations VALUES(136,'Rádio Arena 103.1 FM','https://stm12.xcast.com.br:7672/stream',0);
INSERT INTO stations VALUES(137,'Alternativa Sertaneja','https://stm25.srvaudio.com.br:11068/',0);
INSERT INTO stations VALUES(138,'Rádio Sucesso 87.7 FM','https://stm2.streamproarte.com.br:7196/stream',0);
INSERT INTO stations VALUES(139,'Rádio Onda Livre 105.3 FM','https://centova.svdns.com.br:20016/stream',0);
INSERT INTO stations VALUES(140,'Rádio T 88.1 FM','https://ice.fabricahost.com.br/radiotfoz',0);
INSERT INTO stations VALUES(141,'Rádio Dracena','https://cc3.streammaximum.com:20001/stream',0);
INSERT INTO stations VALUES(142,'Rádio Jovem Pira 102.7 FM','https://servidor23-5.brlogic.com:7722/live',0);
INSERT INTO stations VALUES(143,'Rádio Nova Brasil 89.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/NOVABRASIL_RIOAAC.aac',0);
INSERT INTO stations VALUES(144,'Rádio Clube 99.3 FM','https://server01.ouvir.radio.br:8003/stream',0);
INSERT INTO stations VALUES(145,'MS Web Rádio','https://s25.maxcast.com.br:8108/live',0);
INSERT INTO stations VALUES(146,'Rádio Visionária','https://hts06.kshost.com.br:11956/live',0);
INSERT INTO stations VALUES(147,'Rádio Super Músicas','https://stm17.srvstm.com:7172/',0);
INSERT INTO stations VALUES(148,'Rádio Trans Mundial - RTM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOTRANSMUNDIALAAC_SC',0);
INSERT INTO stations VALUES(149,'Rádio Criativa 98.9 FM','https://streaming.ei3.com.br/radio/8020/radio',0);
INSERT INTO stations VALUES(150,'Flash Disco Dance - Old School','https://stm2.srvif.com:6678/',0);
INSERT INTO stations VALUES(151,'Web Rádio Juac','https://ssl.nortecast.com:7024/',0);
INSERT INTO stations VALUES(152,'Rádio Nativa 93.5 FM','https://ice.fabricahost.com.br/nativafmlitoral',0);
INSERT INTO stations VALUES(153,'Rádio CBN Brasília 95.3 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_BSBAAC.aac?dist=radioscombr',0);
INSERT INTO stations VALUES(154,'Esportes Total','https://s03.maxcast.com.br:8006/live',0);
INSERT INTO stations VALUES(155,'Love Music Fm','https://player.streaminghd.net.br/ssl.php?p=7324&s=stm3',0);
INSERT INTO stations VALUES(156,'Rádio Sinai Web Gospel','https://centova4.transmissaodigital.com:20278/stream',0);
INSERT INTO stations VALUES(157,'Rádio Inconfidência 100.9 FM','https://ssl.zoeweb.net/proxy/inconfidencia?mp=/stream','https://www.radios.com.br/aovivo/radio-inconfidencia-1009-fm/13306',0);
INSERT INTO stations VALUES(158,'Beatles Radio.com','','https://www.radios.com.br/aovivo/beatles-radiocom/17309',0);
INSERT INTO stations VALUES(159,'Rádio Alternativa 104.9 FM','https://conecta.welltecnologia.com.br/radio/8200/stream','https://www.radios.com.br/aovivo/radio-alternativa-1049-fm/8786',0);
INSERT INTO stations VALUES(160,'Rádio Clube Sul de Minas 103.1 FM','https://ice.fabricahost.com.br/clubefmvarginha','https://www.radios.com.br/aovivo/radio-clube-sul-de-minas-1031-fm/14729',0);
INSERT INTO stations VALUES(161,'Rádio Musical Gospel','https://stm1.xcast.com.br:8258/stream','https://www.radios.com.br/aovivo/radio-musical-gospel/136340',0);
INSERT INTO stations VALUES(162,'Bom Gosto','https://ssl.xcast.com.br:11408/stream','https://www.radios.com.br/aovivo/bom-gosto/35810',0);
INSERT INTO stations VALUES(163,'Rádio Nativa 92.5 FM','https://player.srvaudio.com.br/player-ssl/9468/','https://www.radios.com.br/aovivo/radio-nativa-925-fm/30175',0);
INSERT INTO stations VALUES(164,'Rádio João Pessoa 97.7 FM','https://serv3.audiovox.pw:7084/stream','https://www.radios.com.br/aovivo/radio-joao-pessoa-977-fm/178614',0);
INSERT INTO stations VALUES(165,'Radio Rivadavia 630 AM','https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac','https://www.radios.com.br/aovivo/radio-rivadavia-630-am/16738',0);
INSERT INTO stations VALUES(166,'Rádio Mateus 633','','https://www.radios.com.br/aovivo/radio-mateus-633/101265',0);
INSERT INTO stations VALUES(167,'Rádio Gospel Adorando','https://r15.ciclano.io:14391/stream','https://www.radios.com.br/aovivo/radio-gospel-adorando/202810',0);
INSERT INTO stations VALUES(168,'Rádio Onda Sul 94.9 FM','https://ice.fabricahost.com.br/ondasulfm','https://www.radios.com.br/aovivo/radio-onda-sul-949-fm/13882',0);
INSERT INTO stations VALUES(169,'Acesita FM','https://stm1.xcast.com.br:9470/stream','https://www.radios.com.br/aovivo/acesita-fm/25522',0);
INSERT INTO stations VALUES(170,'Radio CBN Grandes Lagos 90.9 FM','','https://www.radios.com.br/aovivo/radio-cbn-grandes-lagos-909-fm/28672',0);
INSERT INTO stations VALUES(171,'Rádio RBN Digital','','https://www.radios.com.br/aovivo/radio-rbn-digital/46251',0);
INSERT INTO stations VALUES(172,'Blu Radio 89.9 FM','','https://www.radios.com.br/aovivo/blu-radio-899-fm/24615',0);
INSERT INTO stations VALUES(173,'MS Web Rádio','https://s25.maxcast.com.br:8108/live','https://www.radios.com.br/aovivo/ms-web-radio/62729',0);
INSERT INTO stations VALUES(174,'Rádio Saudade Web','https://player-ssl.painelstream.net:9036/live','https://www.radios.com.br/aovivo/radio-saudade-web/159795',0);
INSERT INTO stations VALUES(175,'Rádio BandNews 90.7 FM','','https://www.radios.com.br/aovivo/radio-bandnews-907-fm/116924',0);
INSERT INTO stations VALUES(176,'Supernova FM','','https://www.radios.com.br/aovivo/supernova-fm/67803',0);
INSERT INTO stations VALUES(177,'Rádio Nova 89.5 FM','https://server2.webradios.com.br:19128/9128','https://www.radios.com.br/aovivo/radio-nova-895-fm/14090',0);
INSERT INTO stations VALUES(178,'Plus Rádio Fortaleza','https://hts02.kshost.com.br:13168/live','https://www.radios.com.br/aovivo/plus-radio-fortaleza/62229',0);
INSERT INTO stations VALUES(179,'Rádio Band FM 101.1','https://stm01.virtualcast.com.br:8216/live','https://www.radios.com.br/aovivo/radio-band-fm-1011/10385',0);
INSERT INTO stations VALUES(180,'Radio Continental 590 AM','','https://www.radios.com.br/aovivo/radio-continental-590-am/15317',0);
INSERT INTO stations VALUES(181,'Rádio Nova Brasil 89.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/NOVABRASIL_RIOAAC.aac','https://www.radios.com.br/aovivo/radio-nova-brasil-895-fm/72019',0);
INSERT INTO stations VALUES(182,'Rádio 98 FM','https://9554.brasilstream.com.br/stream','https://www.radios.com.br/aovivo/radio-98-fm/18495',0);
INSERT INTO stations VALUES(183,'Radio Oriental 770 AM','','https://www.radios.com.br/aovivo/radio-oriental-770-am/8290',0);
INSERT INTO stations VALUES(184,'Rádio Fonte','','https://www.radios.com.br/aovivo/radio-fonte/56031',0);
INSERT INTO stations VALUES(185,'Rádio Cidade das Águas 101.3 FM','https://str1.streamhostpg.com.br:8008/stream','https://www.radios.com.br/aovivo/radio-cidade-das-aguas-1013-fm/11672',0);
INSERT INTO stations VALUES(186,'Rádio Light 103.9 FM','','https://www.radios.com.br/aovivo/radio-light-1039-fm/13145',0);
INSERT INTO stations VALUES(187,'Batera Rádio Rock','','https://www.radios.com.br/aovivo/batera-radio-rock/155849',0);
INSERT INTO stations VALUES(188,'Rádio Eletrônica Mix Brasil','','https://www.radios.com.br/aovivo/radio-eletronica-mix-brasil/143128',0);
INSERT INTO stations VALUES(189,'Rádio Dracena','https://cc3.streammaximum.com:20001/stream','https://www.radios.com.br/aovivo/radio-dracena/123269',0);
INSERT INTO stations VALUES(190,'Chante France 90.9 FM','','https://www.radios.com.br/aovivo/chante-france-909-fm/12171',0);
INSERT INTO stations VALUES(191,'Radio 24 104.8 FM','','https://www.radios.com.br/aovivo/radio-24-1048-fm/16708',0);
INSERT INTO stations VALUES(192,'RFI Francês 98.7 FM','','https://www.radios.com.br/aovivo/rfi-frances-987-fm/39512',0);
INSERT INTO stations VALUES(193,'Black In Love Radio','https://hts05.kshost.com.br:9890/live','https://www.radios.com.br/aovivo/black-in-love-radio/29203',0);
INSERT INTO stations VALUES(194,'Rádio Hot 107 FM','https://9772.brasilstream.com.br/stream','https://www.radios.com.br/aovivo/radio-hot-107-fm/8760',0);
INSERT INTO stations VALUES(195,'Radio Guavira 103.1 FM','https://player.srvaudio.com.br/player-ssl/11504/','https://www.radios.com.br/aovivo/radio-guavira-1031-fm/33688',0);
INSERT INTO stations VALUES(196,'Rádio Gospel Campinas','','https://www.radios.com.br/aovivo/radio-gospel-campinas/40462',0);
INSERT INTO stations VALUES(197,'Party Web Rádio','','https://www.radios.com.br/aovivo/party-web-radio/193070',0);
INSERT INTO stations VALUES(198,'Rádio Hits 99.7 FM','','https://www.radios.com.br/aovivo/radio-hits-997-fm/8807',0);
INSERT INTO stations VALUES(199,'FFH 105.9 FM Eurodance','','https://www.radios.com.br/aovivo/ffh-1059-fm-eurodance/34847',0);
INSERT INTO stations VALUES(200,'Bons Tempos FM','https://server02.ouvir.radio.br:8050/stream','https://www.radios.com.br/aovivo/bons-tempos-fm/37027',0);
INSERT INTO stations VALUES(201,'Alternativa Esportes Webrádio','https://hts08.kshost.com.br:12592/live','https://www.radios.com.br/aovivo/alternativa-esportes-webradio/69487',0);
INSERT INTO stations VALUES(202,'Rádio Brasil Hits','','https://www.radios.com.br/aovivo/radio-brasil-hits/32433',0);
INSERT INTO stations VALUES(203,'Rádio Maisnova 81.9 FM','','https://www.radios.com.br/aovivo/radio-maisnova-819-fm/194735',0);
INSERT INTO stations VALUES(204,'Rádio Futebol Interior','','https://www.radios.com.br/aovivo/radio-futebol-interior/16685',0);
INSERT INTO stations VALUES(205,'Web Rádio AC Tec','','https://www.radios.com.br/aovivo/web-radio-ac-tec/144268',0);
INSERT INTO stations VALUES(206,'Rádio Super 95.5 FM','','https://www.radios.com.br/aovivo/radio-super-955-fm/32982',0);
INSERT INTO stations VALUES(207,'Radio Love Live','','https://www.radios.com.br/aovivo/radio-love-live/18971',0);
INSERT INTO stations VALUES(208,'Radio Rock On','https://streaming.radiostreamlive.com/radiorockon_devices','https://www.radios.com.br/aovivo/radio-rock-on/57886',0);
INSERT INTO stations VALUES(209,'France Info 105.5 FM','','https://www.radios.com.br/aovivo/france-info-1055-fm/12462',0);
INSERT INTO stations VALUES(210,'Rádio Vida FM Gospel 104.9','','https://www.radios.com.br/aovivo/radio-vida-fm-gospel-1049/14811',0);
INSERT INTO stations VALUES(211,'Rádio CBN Brasília 95.3 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_BSBAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-cbn-brasilia-953-fm/8818',0);
INSERT INTO stations VALUES(212,'Rádio Cordeiro de Deus','','https://www.radios.com.br/aovivo/radio-cordeiro-de-deus/8789',0);
INSERT INTO stations VALUES(213,'Rádio Voz Poços','https://stm1.radionline.top:7088/stream','https://www.radios.com.br/aovivo/radio-voz-pocos/142188',0);
INSERT INTO stations VALUES(214,'Rádio Shekinah só Louvor','https://player.voxpainel.com.br/proxy/7076','https://www.radios.com.br/aovivo/radio-shekinah-so-louvor/15612',0);
INSERT INTO stations VALUES(215,'Rádio Barroso Mix','','https://www.radios.com.br/aovivo/radio-barroso-mix/61109',0);
INSERT INTO stations VALUES(216,'Radio Sport 890 AM','','https://www.radios.com.br/aovivo/radio-sport-890-am/8344',0);
INSERT INTO stations VALUES(217,'Rádio Nova Cultura 93.1 FM','https://streaming.ei3.com.br/radio/8010/stream','https://www.radios.com.br/aovivo/radio-nova-cultura-931-fm/104429',0);
INSERT INTO stations VALUES(218,'Web Rádio 016','','https://www.radios.com.br/aovivo/web-radio-016/195623',0);
INSERT INTO stations VALUES(219,'Rádio 102 FM 102.9','','https://www.radios.com.br/aovivo/radio-102-fm-1029/27',0);
INSERT INTO stations VALUES(220,'Rádio Lupa 1 FM 94.5','','https://www.radios.com.br/aovivo/radio-lupa-1-fm-945/198842',0);
INSERT INTO stations VALUES(221,'Radio Área Deportiva 99.3 FM','','https://www.radios.com.br/aovivo/radio-area-deportiva-993-fm/37858',0);
INSERT INTO stations VALUES(222,'Rádio Globo RJ 98.1 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_GLOBO_RJAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-globo-rj-981-fm/8817',0);
INSERT INTO stations VALUES(223,'Rádio Banda B 550 AM 79.3 FM','https://ice.fabricahost.com.br/bandabctb','https://www.radios.com.br/aovivo/radio-banda-b-550-am-793-fm/10406',0);
INSERT INTO stations VALUES(224,'Rádio Super 91.7 FM','https://9134.brasilstream.com.br/mp3','https://www.radios.com.br/aovivo/radio-super-917-fm/24398',0);
INSERT INTO stations VALUES(225,'Super Rádio Tupi 96.5 FM','https://8923.brasilstream.com.br/stream','https://www.radios.com.br/aovivo/super-radio-tupi-965-fm/14215',0);
INSERT INTO stations VALUES(226,'Rádio Jornal 91.3 FM','','https://www.radios.com.br/aovivo/radio-jornal-913-fm/13492',0);
INSERT INTO stations VALUES(227,'Rádio Tupã 97.7 FM','','https://www.radios.com.br/aovivo/radio-tupa-977-fm/14942',0);
INSERT INTO stations VALUES(228,'Rádio Nova Geração FM','https://www.appradio.app:8152/live','https://www.radios.com.br/aovivo/radio-nova-geracao-fm/32447',0);
INSERT INTO stations VALUES(229,'Radio Antena 2 650 AM','https://playerservices.streamtheworld.com/api/livestream-redirect/ANTENA_2_BOG_SC','https://www.radios.com.br/aovivo/radio-antena-2-650-am/8524',0);
INSERT INTO stations VALUES(230,'Rádio Onda Poços 96.7 FM','','https://www.radios.com.br/aovivo/radio-onda-pocos-967-fm/110666',0);
INSERT INTO stations VALUES(231,'Rádio Liderança 91.3 FM','https://s28.maxcast.com.br:8868/live','https://www.radios.com.br/aovivo/radio-lideranca-913-fm/33672',0);
INSERT INTO stations VALUES(232,'Radio Saudade 99.7 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/SAUDADE_FMAAC.aac','https://www.radios.com.br/aovivo/radio-saudade-997-fm/8',0);
INSERT INTO stations VALUES(233,'Rádio Uirapuru Jaguaribana 91.5 FM','','https://www.radios.com.br/aovivo/radio-uirapuru-jaguaribana-915-fm/25228',0);
INSERT INTO stations VALUES(234,'Radio Gospel Life','https://s15.maxcast.com.br:8296/live','https://www.radios.com.br/aovivo/radio-gospel-life/49251',0);
INSERT INTO stations VALUES(235,'Rádio Super Pajeú 99.3 FM','https://server3.webradios.com.br:19434/9434','https://www.radios.com.br/aovivo/radio-super-pajeu-993-fm/14744',0);
INSERT INTO stations VALUES(236,'Rádio Difusora Pantanal 101.9 FM','','https://www.radios.com.br/aovivo/radio-difusora-pantanal-1019-fm/12797',0);
INSERT INTO stations VALUES(237,'Rede Tudo de Bom','','https://www.radios.com.br/aovivo/rede-tudo-de-bom/15637',0);
INSERT INTO stations VALUES(238,'Radio Dimensione Suono Soft Centro 105.3 FM','','https://www.radios.com.br/aovivo/radio-dimensione-suono-soft-centro-1053-fm/25952',0);
INSERT INTO stations VALUES(239,'Rádio Arena 103.1 FM','https://stm12.xcast.com.br:7672/stream','https://www.radios.com.br/aovivo/radio-arena-1031-fm/24261',0);
INSERT INTO stations VALUES(240,'Rádio Voz Alterosa','','https://www.radios.com.br/aovivo/radio-voz-alterosa/101659',0);
INSERT INTO stations VALUES(241,'Rádio Costa do Sol 101.7 FM','https://ice.fabricahost.com.br/radiocostadosol','https://www.radios.com.br/aovivo/radio-costa-do-sol-1017-fm/12229',0);
INSERT INTO stations VALUES(242,'Caracol Radio 100.9 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CARACOL_RADIOAAC.aac','https://www.radios.com.br/aovivo/caracol-radio-1009-fm/8520',0);
INSERT INTO stations VALUES(243,'Rádio Mega 94 FM','','https://www.radios.com.br/aovivo/radio-mega-94-fm/13840',0);
INSERT INTO stations VALUES(244,'Rádio Antena 1 FM 101.7','','https://www.radios.com.br/aovivo/radio-antena-1-fm-1017/39757',0);
INSERT INTO stations VALUES(245,'Rádio Integração 87.5 FM','https://cast.tendaweb.com.br/proxy/radiointegracaofm?mp=/stream','https://www.radios.com.br/aovivo/radio-integracao-875-fm/19379',0);
INSERT INTO stations VALUES(246,'Rádio Cidade Verde 93.5 FM','','https://www.radios.com.br/aovivo/radio-cidade-verde-935-fm/42987',0);
INSERT INTO stations VALUES(247,'Rádio Positividade 104.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/POSITIVIDADE_FM.mp3','https://www.radios.com.br/aovivo/radio-positividade-1045-fm/181824',0);
INSERT INTO stations VALUES(248,'Rádio Excesso FM 90.9','https://excessocast.com.br/radio/8000/excessofm','https://www.radios.com.br/aovivo/radio-excesso-fm-909/134049',0);
INSERT INTO stations VALUES(249,'Rádio TSF 89.5 FM','','https://www.radios.com.br/aovivo/radio-tsf-895-fm/8959',0);
INSERT INTO stations VALUES(250,'Rádio Jovem Pira 102.7 FM','https://servidor23-5.brlogic.com:7722/live','https://www.radios.com.br/aovivo/radio-jovem-pira-1027-fm/13540',0);
INSERT INTO stations VALUES(251,'Rádio CBN Rio 92.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_RJAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-cbn-rio-925-fm/8819',0);
INSERT INTO stations VALUES(252,'Rádio Renascer FM','','https://www.radios.com.br/aovivo/radio-renascer-fm/204496',0);
INSERT INTO stations VALUES(253,'Rádio Mix Music','','https://www.radios.com.br/aovivo/radio-mix-music/124584',0);
INSERT INTO stations VALUES(254,'Rádio Nova Tupã 100.3 FM','','https://www.radios.com.br/aovivo/radio-nova-tupa-1003-fm/16962',0);
INSERT INTO stations VALUES(255,'Rádio Tropical 95.3 FM','https://solid24.streamupsolutions.com/proxy/dcofieen?mp=/stream','https://www.radios.com.br/aovivo/radio-tropical-953-fm/8958',0);
INSERT INTO stations VALUES(256,'Rádio Visionária','https://hts06.kshost.com.br:11956/live','https://www.radios.com.br/aovivo/radio-visionaria/163920',0);
INSERT INTO stations VALUES(257,'Radio Agricultura 92.1 FM','','https://www.radios.com.br/aovivo/radio-agricultura-921-fm/6464',0);
INSERT INTO stations VALUES(258,'Rádio Máxima 97.1 FM','','https://www.radios.com.br/aovivo/radio-maxima-971-fm/13829',0);
INSERT INTO stations VALUES(259,'Rádio Fan 99.7 FM','','https://www.radios.com.br/aovivo/radio-fan-997-fm/22355',0);
INSERT INTO stations VALUES(260,'Rádio BandNews SP 96.9 FM','','https://www.radios.com.br/aovivo/radio-bandnews-sp-969-fm/24477',0);
INSERT INTO stations VALUES(261,'Rádio Sinai Web Gospel','https://centova4.transmissaodigital.com:20278/stream','https://www.radios.com.br/aovivo/radio-sinai-web-gospel/22540',0);
INSERT INTO stations VALUES(262,'Rádio Gaúcha 93.7 FM','','https://www.radios.com.br/aovivo/radio-gaucha-937-fm/13176',0);
INSERT INTO stations VALUES(263,'Rádio Sol Nascente DF','https://s05.maxcast.com.br:8242/live','https://www.radios.com.br/aovivo/radio-sol-nascente-df/26659',0);
INSERT INTO stations VALUES(264,'Rádio 96 FM Bauru','https://streaming.ei3.com.br/radio/8000/mp3','https://www.radios.com.br/aovivo/radio-96-fm-bauru/8756',0);
INSERT INTO stations VALUES(265,'Rádio Energia 97.7 FM','https://streaming.inweb.com.br/energia','https://www.radios.com.br/aovivo/radio-energia-977-fm/13065',0);
INSERT INTO stations VALUES(266,'Rádio Onda Sul 100.7 FM','https://stm01.virtualcast.com.br:8886/live','https://www.radios.com.br/aovivo/radio-onda-sul-1007-fm/13881',0);
INSERT INTO stations VALUES(267,'1000 Hits Love','https://ais-sa2.cdnstream1.com/2210_128.mp3','https://www.radios.com.br/aovivo/1000-hits-love/47161',0);
INSERT INTO stations VALUES(268,'Rádio BH FM 102.1','https://playerservices.streamtheworld.com/api/livestream-redirect/BHFMAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-bh-fm-1021/8813',0);
INSERT INTO stations VALUES(269,'Rádio Rambo Metal','https://s01.maxcast.com.br:8063/live','https://www.radios.com.br/aovivo/radio-rambo-metal/202912',0);
INSERT INTO stations VALUES(270,'Rádio Itatiaia 610 AM 95.7 FM','','https://www.radios.com.br/aovivo/radio-itatiaia-610-am-957-fm/14',0);
INSERT INTO stations VALUES(271,'Rádio Trans Mundial - RTM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOTRANSMUNDIALAAC_SC','https://www.radios.com.br/aovivo/radio-trans-mundial-rtm/18759',0);
INSERT INTO stations VALUES(272,'Rádio BandNews RJ 90.3 FM','','https://www.radios.com.br/aovivo/radio-bandnews-rj-903-fm/10399',0);
INSERT INTO stations VALUES(273,'Rádio Cristã de Maringá','https://hts03.kshost.com.br:12156/live','https://www.radios.com.br/aovivo/radio-crista-de-maringa/176724',0);
INSERT INTO stations VALUES(274,'Rádio Antena 1 99.4 FM','','https://www.radios.com.br/aovivo/radio-antena-1-994-fm/4749',0);
INSERT INTO stations VALUES(275,'Rádio Reggae 10','','https://www.radios.com.br/aovivo/radio-reggae-10/33913',0);
INSERT INTO stations VALUES(276,'Radio El Espectador 810 AM','https://espectador1.net.com.uy:8122/stream','https://www.radios.com.br/aovivo/radio-el-espectador-810-am/8258',0);
INSERT INTO stations VALUES(277,'Rádio Web SP','','https://www.radios.com.br/aovivo/radio-web-sp/208427',0);
INSERT INTO stations VALUES(278,'Rádio Golo 89.2 FM','','https://www.radios.com.br/aovivo/radio-golo-892-fm/39538',0);
INSERT INTO stations VALUES(279,'Rádio Referência Do Samba','https://stm6.srvvox.com.br:7290/stream','https://www.radios.com.br/aovivo/radio-referencia-do-samba/199001',0);
INSERT INTO stations VALUES(280,'Web Vintage Radio','https://s1.voscast.com:10563/webvintage','https://www.radios.com.br/aovivo/web-vintage-radio/61905',0);
INSERT INTO stations VALUES(281,'DeeJay Radio 97.5 FM','','https://www.radios.com.br/aovivo/deejay-radio-975-fm/143118',0);
INSERT INTO stations VALUES(282,'Rádio Jovem Pan 107.3 FM','https://server01.ouvir.radio.br:8042/stream','https://www.radios.com.br/aovivo/radio-jovem-pan-1073-fm/14660',0);
INSERT INTO stations VALUES(283,'Rádio Fla Gol','https://s17.maxcast.com.br:8168/live?id=824974197929','https://www.radios.com.br/aovivo/radio-fla-gol/195257',0);
INSERT INTO stations VALUES(284,'Rádio Hits 99.7 FM','https://paineldj.com.br:20028/stream','https://www.radios.com.br/aovivo/radio-hits-997-fm/80135',0);
INSERT INTO stations VALUES(285,'Rádio Melodia 102.3 FM','https://server01.ouvir.radio.br:8033/stream','https://www.radios.com.br/aovivo/radio-melodia-1023-fm/8805',0);
INSERT INTO stations VALUES(286,'Rádio Imigrantes 100.9 FM','https://sonic.lestetronics.com.br:7001/','https://www.radios.com.br/aovivo/radio-imigrantes-1009-fm/13421',0);
INSERT INTO stations VALUES(287,'Rádio RFM 93.2 FM','','https://www.radios.com.br/aovivo/radio-rfm-932-fm/8933',0);
INSERT INTO stations VALUES(288,'Rádio Bandeirantes 840 AM 90.9 FM','','https://www.radios.com.br/aovivo/radio-bandeirantes-840-am-909-fm/10410',0);
INSERT INTO stations VALUES(289,'Rádio CV Mais 97.5 FM','https://ssl1.transmissaodigital.com:20098/','https://www.radios.com.br/aovivo/radio-cv-mais-975-fm/157979',0);
INSERT INTO stations VALUES(290,'Rai Radio 1 89.7 FM','','https://www.radios.com.br/aovivo/rai-radio-1-897-fm/12642',0);
INSERT INTO stations VALUES(291,'Rádio Kboing 100.3 FM','','https://www.radios.com.br/aovivo/radio-kboing-1003-fm/29604',0);
INSERT INTO stations VALUES(292,'Rádio CBN São Paulo 90.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_SPAAC.aac','https://www.radios.com.br/aovivo/radio-cbn-sao-paulo-905-fm/8816',0);
INSERT INTO stations VALUES(293,'Web Rádio Piabanha','https://s11.maxcast.com.br:8168/live','https://www.radios.com.br/aovivo/web-radio-piabanha/80640',0);
INSERT INTO stations VALUES(294,'Rádio Saquarema Surf Rock','https://servidor17.brlogic.com:7202/live','https://www.radios.com.br/aovivo/radio-saquarema-surf-rock/181506',0);
INSERT INTO stations VALUES(295,'Rádio Rota Do Rodeio','https://hts04.kshost.com.br:12986/live','https://www.radios.com.br/aovivo/radio-rota-do-rodeio/174753',0);
INSERT INTO stations VALUES(296,'Cidade Light','https://stm1.voxplayer.com.br:7126/','https://www.radios.com.br/aovivo/cidade-light/25821',0);
INSERT INTO stations VALUES(297,'Radio Carve 850 AM','https://radiolatina.live/9202/stream','https://www.radios.com.br/aovivo/radio-carve-850-am/8232',0);
INSERT INTO stations VALUES(298,'Rádio Morada Sertaneja','https://hts02.kshost.com.br:12594/live','https://www.radios.com.br/aovivo/radio-morada-sertaneja/158074',0);
INSERT INTO stations VALUES(299,'Rádio Estação Pop','https://s46.maxcast.com.br:8026/live','https://www.radios.com.br/aovivo/radio-estacao-pop/29801',0);
INSERT INTO stations VALUES(300,'Radio Caravana 750 AM','https://streamingecuador.net:9006/stream','https://www.radios.com.br/aovivo/radio-caravana-750-am/9656',0);
INSERT INTO stations VALUES(301,'Esportes Total','https://s03.maxcast.com.br:8006/live','https://www.radios.com.br/aovivo/esportes-total/170810',0);
INSERT INTO stations VALUES(302,'Rádio Clube News 90.9 FM','https://servidor14-3.brlogic.com:7540/live','https://www.radios.com.br/aovivo/radio-clube-news-909-fm/190913',0);
INSERT INTO stations VALUES(303,'Radio Cooperativa 760 AM 93.3 FM','','https://www.radios.com.br/aovivo/radio-cooperativa-760-am-933-fm/6502',0);
INSERT INTO stations VALUES(304,'Europe 1 104.7 FM','https://ais-live.cloud-services.paris/europe1.mp3','https://www.radios.com.br/aovivo/europe-1-1047-fm/12361',0);
INSERT INTO stations VALUES(305,'Web Rádio Yhave','','https://www.radios.com.br/aovivo/web-radio-yhave/169790',0);
INSERT INTO stations VALUES(306,'Rádio Hits 99.7 FM','https://paineldj.com.br:20028/stream','https://www.radios.com.br/aovivo/radio-hits-997-fm/80135',0);
INSERT INTO stations VALUES(307,'Rádio Rota Do Rodeio','https://hts04.kshost.com.br:12986/live','https://www.radios.com.br/aovivo/radio-rota-do-rodeio/174753',0);
INSERT INTO stations VALUES(308,'Rádio Caiuás','https://s32.maxcast.com.br:8092/live','https://www.radios.com.br/aovivo/radio-caiuas/172703',0);
INSERT INTO stations VALUES(309,'Rádio Capitania','https://hts09.kshost.com.br:12600/live','https://www.radios.com.br/aovivo/radio-capitania/171005',0);
INSERT INTO stations VALUES(310,'Rádio Fla Gol','https://s17.maxcast.com.br:8168/live?id=824974197929','https://www.radios.com.br/aovivo/radio-fla-gol/195257',0);
INSERT INTO stations VALUES(311,'Gama Esportiva','','https://www.radios.com.br/aovivo/gama-esportiva/65121',0);
INSERT INTO stations VALUES(312,'Rádio Na Voz Delas','https://player.painelvox.com/player-ssl/8694','https://www.radios.com.br/aovivo/radio-na-voz-delas/176151',0);
INSERT INTO stations VALUES(313,'Rádio Arena 103.1 FM','https://stm12.xcast.com.br:7672/stream','https://www.radios.com.br/aovivo/radio-arena-1031-fm/24261',0);
INSERT INTO stations VALUES(314,'Rádio CBN Brasília 95.3 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_BSBAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-cbn-brasilia-953-fm/8818',0);
INSERT INTO stations VALUES(315,'Flash Disco Dance 80','https://stm1.srvif.com:6676/','https://www.radios.com.br/aovivo/flash-disco-dance-80/135855',0);
INSERT INTO stations VALUES(316,'MS Web Rádio','https://s25.maxcast.com.br:8108/live','https://www.radios.com.br/aovivo/ms-web-radio/62729',0);
INSERT INTO stations VALUES(317,'Rádio Web SP','','https://www.radios.com.br/aovivo/radio-web-sp/208427',0);
INSERT INTO stations VALUES(318,'Rádio Band 95.5 FM','https://cast4.hoost.com.br:20216/stream','https://www.radios.com.br/aovivo/radio-band-955-fm/69115',0);
INSERT INTO stations VALUES(319,'Rádio BandNews 90.7 FM','','https://www.radios.com.br/aovivo/radio-bandnews-907-fm/116924',0);
INSERT INTO stations VALUES(320,'Rádio Vida Melhor 105.5 FM','https://servidor32-4.brlogic.com:8480/live','https://www.radios.com.br/aovivo/radio-vida-melhor-1055-fm/61953',0);
INSERT INTO stations VALUES(321,'Rádio BandNews SP 96.9 FM','','https://www.radios.com.br/aovivo/radio-bandnews-sp-969-fm/24477',0);
INSERT INTO stations VALUES(322,'Rádio Gospel Adorando','https://r15.ciclano.io:14391/stream','https://www.radios.com.br/aovivo/radio-gospel-adorando/202810',0);
INSERT INTO stations VALUES(323,'Rádio Trans Mundial - RTM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOTRANSMUNDIALAAC_SC','https://www.radios.com.br/aovivo/radio-trans-mundial-rtm/18759',0);
INSERT INTO stations VALUES(324,'Web Vinil RN','https://ssl.srvstm.com:6704/','https://www.radios.com.br/aovivo/web-vinil-rn/164805',0);
INSERT INTO stations VALUES(325,'Rádio BH FM 102.1','https://playerservices.streamtheworld.com/api/livestream-redirect/BHFMAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-bh-fm-1021/8813',0);
INSERT INTO stations VALUES(326,'Rádio Zonadez','https://stm22.srvaudio.com.br:10056/stream','https://www.radios.com.br/aovivo/radio-zonadez/209577',0);
INSERT INTO stations VALUES(327,'Rádio Globo RJ 98.1 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_GLOBO_RJAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-globo-rj-981-fm/8817',0);
INSERT INTO stations VALUES(328,'Rádio Keops FM','https://player.srvsh.com.br/proxy/7016','https://www.radios.com.br/aovivo/radio-keops-fm/178008',0);
INSERT INTO stations VALUES(329,'Rádio Gospel Campinas','','https://www.radios.com.br/aovivo/radio-gospel-campinas/40462',0);
INSERT INTO stations VALUES(330,'Flash Disco Dance','https://stm1.srvif.com:21764/','https://www.radios.com.br/aovivo/flash-disco-dance/49836',0);
INSERT INTO stations VALUES(331,'Radio Saudade 99.7 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/SAUDADE_FMAAC.aac','https://www.radios.com.br/aovivo/radio-saudade-997-fm/8',0);
INSERT INTO stations VALUES(332,'Rádio Fonte','','https://www.radios.com.br/aovivo/radio-fonte/56031',0);
INSERT INTO stations VALUES(333,'Rádio Cordeiro de Deus','','https://www.radios.com.br/aovivo/radio-cordeiro-de-deus/8789',0);
INSERT INTO stations VALUES(334,'Disco Funk','https://s30.maxcast.com.br:8084/live','https://www.radios.com.br/aovivo/disco-funk/44516',0);
INSERT INTO stations VALUES(335,'Rádio CV Mais 97.5 FM','https://ssl1.transmissaodigital.com:20098/','https://www.radios.com.br/aovivo/radio-cv-mais-975-fm/157979',0);
INSERT INTO stations VALUES(336,'Alternativa Esportes Webrádio','https://hts08.kshost.com.br:12592/live','https://www.radios.com.br/aovivo/alternativa-esportes-webradio/69487',0);
INSERT INTO stations VALUES(337,'Cidade Light','https://stm1.voxplayer.com.br:7126/','https://www.radios.com.br/aovivo/cidade-light/25821',0);
INSERT INTO stations VALUES(338,'Rádio Super Músicas','https://stm17.srvstm.com:7172/','https://www.radios.com.br/aovivo/radio-super-musicas/26355',0);
INSERT INTO stations VALUES(339,'Rádio Mega 94 FM','','https://www.radios.com.br/aovivo/radio-mega-94-fm/13840',0);
INSERT INTO stations VALUES(340,'Rádio Saquarema Surf Rock','https://servidor17.brlogic.com:7202/live','https://www.radios.com.br/aovivo/radio-saquarema-surf-rock/181506',0);
INSERT INTO stations VALUES(341,'Rádio Nova Cultura 93.1 FM','https://streaming.ei3.com.br/radio/8010/stream','https://www.radios.com.br/aovivo/radio-nova-cultura-931-fm/104429',0);
INSERT INTO stations VALUES(342,'Radio Fama 105.0 FM','','https://www.radios.com.br/aovivo/radio-fama-1050-fm/147438',0);
INSERT INTO stations VALUES(343,'Rádio Liderança 91.3 FM','https://s28.maxcast.com.br:8868/live','https://www.radios.com.br/aovivo/radio-lideranca-913-fm/33672',0);
INSERT INTO stations VALUES(344,'Rádio 102 FM 102.9','','https://www.radios.com.br/aovivo/radio-102-fm-1029/27',0);
INSERT INTO stations VALUES(345,'Radio Fama Canal 2 96.4 FM','','https://www.radios.com.br/aovivo/radio-fama-canal-2-964-fm/150198',0);
INSERT INTO stations VALUES(346,'Acesita FM','https://stm1.xcast.com.br:9470/stream','https://www.radios.com.br/aovivo/acesita-fm/25522',0);
INSERT INTO stations VALUES(347,'Web Rádio 016','','https://www.radios.com.br/aovivo/web-radio-016/195623',0);
INSERT INTO stations VALUES(348,'Rádio Visionária','https://hts06.kshost.com.br:11956/live','https://www.radios.com.br/aovivo/radio-visionaria/163920',0);
INSERT INTO stations VALUES(349,'Rádio Nativa 106.1 FM','','https://www.radios.com.br/aovivo/radio-nativa-1061-fm/12812',0);
INSERT INTO stations VALUES(350,'Web Rádio AC Tec','','https://www.radios.com.br/aovivo/web-radio-ac-tec/144268',0);
INSERT INTO stations VALUES(351,'Rádio Antena 1 FM 101.7','','https://www.radios.com.br/aovivo/radio-antena-1-fm-1017/39757',0);
INSERT INTO stations VALUES(352,'Rádio Hits HD','https://casthttps1.suaradionanet.net/13388/stream','https://www.radios.com.br/aovivo/radio-hits-hd/198476',0);
INSERT INTO stations VALUES(353,'Esportes Total','https://s03.maxcast.com.br:8006/live','https://www.radios.com.br/aovivo/esportes-total/170810',0);
INSERT INTO stations VALUES(354,'Rádio Sinai Web Gospel','https://centova4.transmissaodigital.com:20278/stream','https://www.radios.com.br/aovivo/radio-sinai-web-gospel/22540',0);
INSERT INTO stations VALUES(355,'Rádio RVS 95.7 FM','','https://www.radios.com.br/aovivo/radio-rvs-957-fm/14692',0);
INSERT INTO stations VALUES(356,'Rádio Dracena','https://cc3.streammaximum.com:20001/stream','https://www.radios.com.br/aovivo/radio-dracena/123269',0);
INSERT INTO stations VALUES(357,'Rádio Light 103.9 FM','','https://www.radios.com.br/aovivo/radio-light-1039-fm/13145',0);
INSERT INTO stations VALUES(358,'Batera Rádio Rock','','https://www.radios.com.br/aovivo/batera-radio-rock/155849',0);
INSERT INTO stations VALUES(359,'Rádio Barroso Mix','','https://www.radios.com.br/aovivo/radio-barroso-mix/61109',0);
INSERT INTO stations VALUES(360,'Rádio Tom Brasil','https://streaming.radioempresabrasil.com.br/proxy/tombrasil/stream','https://www.radios.com.br/aovivo/radio-tom-brasil/40418',0);
INSERT INTO stations VALUES(361,'Rádio Grande Serra 90.9 FM','https://streaming.rmpsite.com.br/rgsararipina/','https://www.radios.com.br/aovivo/radio-grande-serra-909-fm/13344',0);
INSERT INTO stations VALUES(362,'Rádio Sol Nascente DF','https://s05.maxcast.com.br:8242/live','https://www.radios.com.br/aovivo/radio-sol-nascente-df/26659',0);
INSERT INTO stations VALUES(363,'Rádio Clube 99.3 FM','https://server01.ouvir.radio.br:8003/stream','https://www.radios.com.br/aovivo/radio-clube-993-fm/14659',0);
INSERT INTO stations VALUES(364,'Rádio Ativa Mais HD','https://player.srvaudio.com.br/player-ssl/11460/','https://www.radios.com.br/aovivo/radio-ativa-mais-hd/47591',0);
INSERT INTO stations VALUES(365,'Rádio Nova Brasil 89.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/NOVABRASIL_RIOAAC.aac','https://www.radios.com.br/aovivo/radio-nova-brasil-895-fm/72019',0);
INSERT INTO stations VALUES(366,'Web Rádio Juac','https://ssl.nortecast.com:7024/','https://www.radios.com.br/aovivo/web-radio-juac/142943',0);
INSERT INTO stations VALUES(367,'Alternativa Sertaneja','https://stm25.srvaudio.com.br:11068/','https://www.radios.com.br/aovivo/alternativa-sertaneja/99250',0);
INSERT INTO stations VALUES(368,'Rádio Reggae 10','','https://www.radios.com.br/aovivo/radio-reggae-10/33913',0);
INSERT INTO stations VALUES(369,'Rádio Cidade Verde 93.5 FM','','https://www.radios.com.br/aovivo/radio-cidade-verde-935-fm/42987',0);
INSERT INTO stations VALUES(370,'Rádio Voz Alterosa','','https://www.radios.com.br/aovivo/radio-voz-alterosa/101659',0);
INSERT INTO stations VALUES(371,'Rádio Gaúcha 93.7 FM','','https://www.radios.com.br/aovivo/radio-gaucha-937-fm/13176',0);
INSERT INTO stations VALUES(372,'Rádio Sucesso 87.7 FM','https://stm2.streamproarte.com.br:7196/stream','https://www.radios.com.br/aovivo/radio-sucesso-877-fm/108385',0);
INSERT INTO stations VALUES(373,'Rádio Itatiaia 610 AM 95.7 FM','','https://www.radios.com.br/aovivo/radio-itatiaia-610-am-957-fm/14',0);
INSERT INTO stations VALUES(374,'Rádio Lupa 1 FM 94.5','','https://www.radios.com.br/aovivo/radio-lupa-1-fm-945/198842',0);
INSERT INTO stations VALUES(375,'Rádio Difusora Pantanal 101.9 FM','','https://www.radios.com.br/aovivo/radio-difusora-pantanal-1019-fm/12797',0);
INSERT INTO stations VALUES(376,'Rádio Cidade das Águas 101.3 FM','https://str1.streamhostpg.com.br:8008/stream','https://www.radios.com.br/aovivo/radio-cidade-das-aguas-1013-fm/11672',0);
INSERT INTO stations VALUES(377,'Rádio Excesso FM 90.9','https://excessocast.com.br/radio/8000/excessofm','https://www.radios.com.br/aovivo/radio-excesso-fm-909/134049',0);
INSERT INTO stations VALUES(378,'Rádio Fan 99.7 FM','','https://www.radios.com.br/aovivo/radio-fan-997-fm/22355',0);
INSERT INTO stations VALUES(379,'Flash Disco Dance - Old School','https://stm2.srvif.com:6678/','https://www.radios.com.br/aovivo/flash-disco-dance-old-school/167915',0);
INSERT INTO stations VALUES(380,'Bailinho De Garagem','','https://www.radios.com.br/aovivo/bailinho-de-garagem/42243',0);
INSERT INTO stations VALUES(381,'Rádio Terra MS','','https://www.radios.com.br/aovivo/radio-terra-ms/61133',0);
INSERT INTO stations VALUES(382,'Rádio Nova Tupã 100.3 FM','','https://www.radios.com.br/aovivo/radio-nova-tupa-1003-fm/16962',0);
INSERT INTO stations VALUES(383,'Rádio Sucesso 98.3 FM','','https://www.radios.com.br/aovivo/radio-sucesso-983-fm/14717',0);
INSERT INTO stations VALUES(384,'Web Rádio Verdão','https://s45.hstbr.net:8062/live','https://www.radios.com.br/aovivo/web-radio-verdao/22463',0);
INSERT INTO stations VALUES(385,'Web Rádio Yhave','','https://www.radios.com.br/aovivo/web-radio-yhave/169790',0);
INSERT INTO stations VALUES(386,'Rádio Gospel Central','','https://www.radios.com.br/aovivo/radio-gospel-central/155689',0);
INSERT INTO stations VALUES(387,'Vision Web Rádio','','https://www.radios.com.br/aovivo/vision-web-radio/28955',0);
INSERT INTO stations VALUES(388,'Rádio Futebol Interior','','https://www.radios.com.br/aovivo/radio-futebol-interior/16685',0);
INSERT INTO stations VALUES(389,'Rádio Sol Nascente','','https://www.radios.com.br/aovivo/radio-sol-nascente/208968',0);
INSERT INTO stations VALUES(390,'Rádio Inconfidentes 87.9 FM','','https://www.radios.com.br/aovivo/radio-inconfidentes-879-fm/13430',0);
INSERT INTO stations VALUES(391,'Rádio Dence','','https://www.radios.com.br/aovivo/radio-dence/8853',0);
INSERT INTO stations VALUES(392,'Rádio Bandeirantes 840 AM 90.9 FM','','https://www.radios.com.br/aovivo/radio-bandeirantes-840-am-909-fm/10410',0);
INSERT INTO stations VALUES(393,'Rádio Onda Livre 105.3 FM','https://centova.svdns.com.br:20016/stream','https://www.radios.com.br/aovivo/radio-onda-livre-1053-fm/13877',0);
INSERT INTO stations VALUES(394,'Rádio Alternativa 104.9 FM','https://conecta.welltecnologia.com.br/radio/8200/stream','https://www.radios.com.br/aovivo/radio-alternativa-1049-fm/8786',0);
INSERT INTO stations VALUES(395,'Rádio 96 FM Bauru','https://streaming.ei3.com.br/radio/8000/mp3','https://www.radios.com.br/aovivo/radio-96-fm-bauru/8756',0);
INSERT INTO stations VALUES(396,'Rádio Brasil Hits','','https://www.radios.com.br/aovivo/radio-brasil-hits/32433',0);
INSERT INTO stations VALUES(397,'Rádio Nativa 93.5 FM','https://ice.fabricahost.com.br/nativafmlitoral','https://www.radios.com.br/aovivo/radio-nativa-935-fm/117114',0);
INSERT INTO stations VALUES(398,'Rádio João Pessoa 97.7 FM','https://serv3.audiovox.pw:7084/stream','https://www.radios.com.br/aovivo/radio-joao-pessoa-977-fm/178614',0);
INSERT INTO stations VALUES(399,'Love Music Fm','https://player.streaminghd.net.br/ssl.php?p=7324&s=stm3','https://www.radios.com.br/aovivo/love-music-fm/43334',0);
INSERT INTO stations VALUES(400,'Rádio Hot 107 FM','https://9772.brasilstream.com.br/stream','https://www.radios.com.br/aovivo/radio-hot-107-fm/8760',0);
INSERT INTO stations VALUES(401,'Bons Tempos FM','https://server02.ouvir.radio.br:8050/stream','https://www.radios.com.br/aovivo/bons-tempos-fm/37027',0);
INSERT INTO stations VALUES(402,'Web Vintage Radio','https://s1.voscast.com:10563/webvintage','https://www.radios.com.br/aovivo/web-vintage-radio/61905',0);
INSERT INTO stations VALUES(403,'Rádio Brasil Cidadão','','https://www.radios.com.br/aovivo/radio-brasil-cidadao/160680',0);
INSERT INTO stations VALUES(404,'Rádio CBN Rio 92.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_RJAAC.aac?dist=radioscombr','https://www.radios.com.br/aovivo/radio-cbn-rio-925-fm/8819',0);
INSERT INTO stations VALUES(405,'Rádio Cidade Itajubá Light','https://cast4.zadax.com.br:8104/live','https://www.radios.com.br/aovivo/radio-cidade-itajuba-light/19783',0);
INSERT INTO stations VALUES(406,'Rádio Invasora 1','','https://www.radios.com.br/aovivo/radio-invasora-1/166480',0);
INSERT INTO stations VALUES(407,'Radio Jazz Medley','https://server01.ouvir.radio.br:8006/stream','https://www.radios.com.br/aovivo/radio-jazz-medley/8845',0);
INSERT INTO stations VALUES(408,'Super Rádio Tupi 96.5 FM','https://8923.brasilstream.com.br/stream','https://www.radios.com.br/aovivo/super-radio-tupi-965-fm/14215',0);
INSERT INTO stations VALUES(409,'Rádio RBN Digital','','https://www.radios.com.br/aovivo/radio-rbn-digital/46251',0);
INSERT INTO stations VALUES(410,'Rádio Jovem Pira 102.7 FM','https://servidor23-5.brlogic.com:7722/live','https://www.radios.com.br/aovivo/radio-jovem-pira-1027-fm/13540',0);
INSERT INTO stations VALUES(411,'Rádio Nova Geração FM','https://www.appradio.app:8152/live','https://www.radios.com.br/aovivo/radio-nova-geracao-fm/32447',0);
INSERT INTO stations VALUES(412,'Rádio Canoa Grande 90.7 FM','https://servidor39.brlogic.com:8300/live','https://www.radios.com.br/aovivo/radio-canoa-grande-907-fm/70055',0);
INSERT INTO stations VALUES(413,'Rádio Criativa 98.9 FM','https://streaming.ei3.com.br/radio/8020/radio','https://www.radios.com.br/aovivo/radio-criativa-989-fm/12237',0);
INSERT INTO stations VALUES(414,'Rádio Energia 97.7 FM','https://streaming.inweb.com.br/energia','https://www.radios.com.br/aovivo/radio-energia-977-fm/13065',0);
INSERT INTO stations VALUES(415,'Rádio Rambo Metal','https://s01.maxcast.com.br:8063/live','https://www.radios.com.br/aovivo/radio-rambo-metal/202912',0);
INSERT INTO stations VALUES(416,'Rádio T 88.1 FM','https://ice.fabricahost.com.br/radiotfoz','https://www.radios.com.br/aovivo/radio-t-881-fm/69511',0);
INSERT INTO stations VALUES(417,'Rádio Shekinah só Louvor','https://player.voxpainel.com.br/proxy/7076','https://www.radios.com.br/aovivo/radio-shekinah-so-louvor/15612',0);
INSERT INTO stations VALUES(418,'Radio Gospel Life','https://s15.maxcast.com.br:8296/live','https://www.radios.com.br/aovivo/radio-gospel-life/49251',0);
INSERT INTO stations VALUES(419,'Rádio CBN São Paulo 90.5 FM','https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_SPAAC.aac','https://www.radios.com.br/aovivo/radio-cbn-sao-paulo-905-fm/8816',0);
INSERT INTO stations VALUES(420,'Rádio Costa do Sol 101.7 FM','https://ice.fabricahost.com.br/radiocostadosol','https://www.radios.com.br/aovivo/radio-costa-do-sol-1017-fm/12229',0);
INSERT INTO stations VALUES(421,'Rádio Clube News 90.9 FM','https://servidor14-3.brlogic.com:7540/live','https://www.radios.com.br/aovivo/radio-clube-news-909-fm/190913',0);
INSERT INTO stations VALUES(422,'Rádio Super Gospel Vale','https://ssl.hdradios.net:7394/stream','https://www.radios.com.br/aovivo/radio-super-gospel-vale/198548',0);
INSERT INTO stations VALUES(423,'Rádio Band FM 101.1','https://stm01.virtualcast.com.br:8216/live','https://www.radios.com.br/aovivo/radio-band-fm-1011/10385',0);
INSERT INTO stations VALUES(424,'Rádio Kboing 100.3 FM','','https://www.radios.com.br/aovivo/radio-kboing-1003-fm/29604',0);
INSERT INTO stations VALUES(425,'Rádio Super 95.5 FM','','https://www.radios.com.br/aovivo/radio-super-955-fm/32982',0);
INSERT INTO stations VALUES(426,'Beat Street','','https://www.radios.com.br/aovivo/beat-street/192584',0);
INSERT INTO stations VALUES(427,'Rádio Hits 99.7 FM','','https://www.radios.com.br/aovivo/radio-hits-997-fm/8807',0);
INSERT INTO stations VALUES(428,'Rádio Tupã 97.7 FM','','https://www.radios.com.br/aovivo/radio-tupa-977-fm/14942',0);
INSERT INTO stations VALUES(429,'Rádio Jornal 91.3 FM','','https://www.radios.com.br/aovivo/radio-jornal-913-fm/13492',0);
INSERT INTO stations VALUES(430,'Rádio Mix Music','','https://www.radios.com.br/aovivo/radio-mix-music/124584',0);
INSERT INTO stations VALUES(431,'Rádio Maisnova 81.9 FM','','https://www.radios.com.br/aovivo/radio-maisnova-819-fm/194735',0);
INSERT INTO stations VALUES(432,'Rádio Serra 88.5 FM','','https://www.radios.com.br/aovivo/radio-serra-885-fm/14573',0);
INSERT INTO stations VALUES(433,'CBN','http://ceb1.live.upx.net.br:8030/stream.aac',1);
INSERT INTO stations VALUES(434,'JP','http://paineldj2.com.br:8200',1);
INSERT INTO stations VALUES(435,'JovemPanNews','http://playerservices.streamtheworld.com/api/livestream-redirect/JP_NEWSAAC.aac',1);
INSERT INTO stations VALUES(436,'Educadora','http://167.114.103.39:8766/stream',1);
INSERT INTO stations VALUES(437,'Laser','http://xh9wo.srv27.brasilstream.com.br:8577/stream',1);
INSERT INTO stations VALUES(438,'Central','http://20823.live.streamtheworld.com/RADIOCENTRAL_AM_SC',1);
INSERT INTO stations VALUES(439,'BandNews','http://evpp.mm.uol.com.br/band/bandnewsfm_sp/playlist.m3u8',1);
INSERT INTO stations VALUES(440,'Antena1','http://antena1.newradio.it/stream',1);
INSERT INTO stations VALUES(441,'Kiss','-playlist https://cloud2.cdnseguro.com:20000/listen.pls',1);
INSERT INTO stations VALUES(442,'Gazeta','-playlist https://shout25.crossradio.com.br:18156/listen.pls',1);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('stations',442);
COMMIT;
